version: "3"

services:

  moh-web3-redis:
    image: "redis:7"
    container_name: "moh-web3-redis"
    restart: always

  moh-web3-postgres:
    image: "postgres:16.2"
    container_name: "moh-web3-postgres"
    volumes:
      - "./dbimg/data:/var/lib/postgresql/data"
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

  moh-web3-nextjs:
    image: "node:20"
    container_name: "moh-web3-nextjs"
    entrypoint: "/bin/bash"
    command: "/workspace/web-app/startup.sh"
    volumes:
      - ".:/workspace"
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env

  moh-web3-flask:
    image: "python:3.11"
    container_name: "moh-web3-flask"
    entrypoint: "/bin/bash"
    command: "/workspace/api/startup.sh"
    volumes:
      - ".:/workspace"
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
